### ISSUE TITLE
Tokyo Disney Land & Tokyo Disney Sea get wait time was broken

### ISSUE THREAD

**Issue by tericky** [cubehouse/wdwJS#16] opened 2016-03-14 13:24 UTC
Hi,

The Tokyo disney get wait time function looks something wrong with API, every attraction always return "Closed" type, and the time wrong too.
Maybe it is relate to request of the realtime url?

**Comment by cubehouse** [comment] 2016-03-14 14:32
What version of wdwjs are you using? And at what time did you make the request?

I can't test right now, since it's nearly midnight and the park is legitimately closed :) Will test later today though to try and reproduce

**Comment by tericky** [comment] 2016-03-14 15:06
I use the version is 3.0.6, and it was wrong from morning before 8 A.M (Japan timezone).
I clone and try it all my day, the message always said : "運営状況の確認には位置情報の送信が必要です。"
It is means that "You need send your location info for checking attractions status"

I'm pretty sure that yesterday was good.

**Comment by cubehouse** [comment] 2016-03-14 15:09
Aha! That is interesting. I think they might have changed how they check you're inside the park...

When I wrote the code, the webpage would request your geo-location and send your longitude and latitude to an API, which would set a cookie to confirm you're in that spot.
So, I just invent a longitude/latitude pair randomly within the parks grounds and send that and store the returned cookie.

I'm guessing they have changed how this setup works, I'll have a poke tonight (I'm in GMT), or if you can fathom how it's put together, feel free to make a Pull Request (that would be very exciting for me!).

Thank you for the bug report, it makes me really glad when people report things so we can keep this library correct and working!

**Comment by tericky** [comment] 2016-03-14 15:28
You know what! They don't change the rule of make sure you are in the park. Because I write a testing script and works good.

So, I think the point might be the SetupAPI function need some fix. When I find it out, then push and make Pull Request.

Have fun tonight :)

**Comment by cubehouse** [comment] 2016-03-14 23:25
Pushed a commit to master that may fix this.

https://github.com/cubehouse/wdwJS/commit/36c3282037b4282b87fb23dfb7d2b64a13e7378a

Let me know if that looks good, I think this was a mistake introduced with the recent addition to the ride opening/closing times being added.

**Comment by cubehouse** [comment] 2016-03-15 08:29
Merged in #17 

Thanks :)

**Closed by cubehouse** 2016-03-15 08:29 UTC
